westpointboxing/config/routes.rb
Westpointboxing::Application.routes.draw do
  resources :coaches

  resources :boxers

end

westpointboxing/app/models/boxer.rb
class Boxer < ActiveRecord::Base
end

westpointboxing/app/models/coach.rb
class Coach < ActiveRecord::Base
end

westpointboxing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

westpointboxing/app/controllers/boxers_controller.rb
class BoxersController < ApplicationController
  # GET /boxers
  # GET /boxers.json
  def index
    @boxers = Boxer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @boxers }
    end
  end

  # GET /boxers/1
  # GET /boxers/1.json
  def show
    @boxer = Boxer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @boxer }
    end
  end

  # GET /boxers/new
  # GET /boxers/new.json
  def new
    @boxer = Boxer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @boxer }
    end
  end

  # GET /boxers/1/edit
  def edit
    @boxer = Boxer.find(params[:id])
  end

  # POST /boxers
  # POST /boxers.json
  def create
    @boxer = Boxer.new(params[:boxer])

    respond_to do |format|
      if @boxer.save
        format.html { redirect_to @boxer, :notice => 'Boxer was successfully created.' }
        format.json { render :json => @boxer, :status => :created, :location => @boxer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @boxer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boxers/1
  # PUT /boxers/1.json
  def update
    @boxer = Boxer.find(params[:id])

    respond_to do |format|
      if @boxer.update_attributes(params[:boxer])
        format.html { redirect_to @boxer, :notice => 'Boxer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @boxer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boxers/1
  # DELETE /boxers/1.json
  def destroy
    @boxer = Boxer.find(params[:id])
    @boxer.destroy

    respond_to do |format|
      format.html { redirect_to boxers_url }
      format.json { head :ok }
    end
  end
end

westpointboxing/app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @coaches }
    end
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
    @coach = Coach.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @coach }
    end
  end

  # GET /coaches/new
  # GET /coaches/new.json
  def new
    @coach = Coach.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @coach }
    end
  end

  # GET /coaches/1/edit
  def edit
    @coach = Coach.find(params[:id])
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(params[:coach])

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, :notice => 'Coach was successfully created.' }
        format.json { render :json => @coach, :status => :created, :location => @coach }
      else
        format.html { render :action => "new" }
        format.json { render :json => @coach.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /coaches/1
  # PUT /coaches/1.json
  def update
    @coach = Coach.find(params[:id])

    respond_to do |format|
      if @coach.update_attributes(params[:coach])
        format.html { redirect_to @coach, :notice => 'Coach was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @coach.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach = Coach.find(params[:id])
    @coach.destroy

    respond_to do |format|
      format.html { redirect_to coaches_url }
      format.json { head :ok }
    end
  end
end

westpointboxing/app/helpers/application_helper.rb
module ApplicationHelper
end

westpointboxing/app/helpers/boxers_helper.rb
module BoxersHelper
end

westpointboxing/app/helpers/coaches_helper.rb
module CoachesHelper
end

westpointboxing/app/views/boxers/_form.html.erb
<%= form_for(@boxer) do |f| %>
  <% if @boxer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boxer.errors.count, "error") %> prohibited this boxer from being saved:</h2>

      <ul>
      <% @boxer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :middleinitial %><br />
    <%= f.text_field :middleinitial %>
  </div>
  <div class="field">
    <%= f.label :xNumber %><br />
    <%= f.text_field :xNumber %>
  </div>
  <div class="field">
    <%= f.label :gradyear %><br />
    <%= f.number_field :gradyear %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

westpointboxing/app/views/boxers/edit.html.erb
<h1>Editing boxer</h1>

<%= render 'form' %>

<%= link_to 'Show', @boxer %> |
<%= link_to 'Back', boxers_path %>

westpointboxing/app/views/boxers/index.html.erb
<h1>Listing boxers</h1>

<table>
  <tr>
    <th>Lastname</th>
    <th>Firstname</th>
    <th>Middleinitial</th>
    <th>Xnumber</th>
    <th>Gradyear</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boxers.each do |boxer| %>
  <tr>
    <td><%= boxer.lastname %></td>
    <td><%= boxer.firstname %></td>
    <td><%= boxer.middleinitial %></td>
    <td><%= boxer.xNumber %></td>
    <td><%= boxer.gradyear %></td>
    <td><%= link_to 'Show', boxer %></td>
    <td><%= link_to 'Edit', edit_boxer_path(boxer) %></td>
    <td><%= link_to 'Destroy', boxer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Boxer', new_boxer_path %>

westpointboxing/app/views/boxers/new.html.erb
<h1>New boxer</h1>

<%= render 'form' %>

<%= link_to 'Back', boxers_path %>

westpointboxing/app/views/boxers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lastname:</b>
  <%= @boxer.lastname %>
</p>

<p>
  <b>Firstname:</b>
  <%= @boxer.firstname %>
</p>

<p>
  <b>Middleinitial:</b>
  <%= @boxer.middleinitial %>
</p>

<p>
  <b>Xnumber:</b>
  <%= @boxer.xNumber %>
</p>

<p>
  <b>Gradyear:</b>
  <%= @boxer.gradyear %>
</p>


<%= link_to 'Edit', edit_boxer_path(@boxer) %> |
<%= link_to 'Back', boxers_path %>

westpointboxing/app/views/coaches/_form.html.erb
<%= form_for(@coach) do |f| %>
  <% if @coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
      <% @coach.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :middleinitial %><br />
    <%= f.text_field :middleinitial %>
  </div>
  <div class="field">
    <%= f.label :xNumber %><br />
    <%= f.text_field :xNumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

westpointboxing/app/views/coaches/edit.html.erb
<h1>Editing coach</h1>

<%= render 'form' %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

westpointboxing/app/views/coaches/index.html.erb
<h1>Listing coaches</h1>

<table>
  <tr>
    <th>Lastname</th>
    <th>Firstname</th>
    <th>Middleinitial</th>
    <th>Xnumber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @coaches.each do |coach| %>
  <tr>
    <td><%= coach.lastname %></td>
    <td><%= coach.firstname %></td>
    <td><%= coach.middleinitial %></td>
    <td><%= coach.xNumber %></td>
    <td><%= link_to 'Show', coach %></td>
    <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
    <td><%= link_to 'Destroy', coach, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Coach', new_coach_path %>

westpointboxing/app/views/coaches/new.html.erb
<h1>New coach</h1>

<%= render 'form' %>

<%= link_to 'Back', coaches_path %>

westpointboxing/app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lastname:</b>
  <%= @coach.lastname %>
</p>

<p>
  <b>Firstname:</b>
  <%= @coach.firstname %>
</p>

<p>
  <b>Middleinitial:</b>
  <%= @coach.middleinitial %>
</p>

<p>
  <b>Xnumber:</b>
  <%= @coach.xNumber %>
</p>


<%= link_to 'Edit', edit_coach_path(@coach) %> |
<%= link_to 'Back', coaches_path %>

westpointboxing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Westpointboxing</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>